server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
## 连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '123'
  #  设置静态资源路径  可从外部直接访问
  resources:
    static-locations:  classpath:/html/,classpath:/static/
## 整合jpa
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
## 整合MyBatis  须在启动类加上@MapperScan注解(dao所在的包) 或者 在每个dao加上@Mapper注解
# mybatis.config= classpath:mybatis-config.xml
mybatis:
  mapperLocations: classpath:mappers/*/*.xml,classpath:mappers/*.xml

logging:
  level:
    com:
      lwp:
        comment:
          blogcomment: debug


